version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploaded_files:/app/uploaded_files
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
